version: '2'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=database7
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    
  app:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    links:
      - db
    ports:
      - 3306:3306
    volumes:
      - /sessions
  spring -boot-jpa-app :
    image: spring-boot-jpa-image
    build:
    context: ./
    dockerfile: Dockerfile
    depends_on:
      -db
    ports:
      - 8080:8080
    volumes:
      - /data/spring-boot-app
    